on:
  push:
    branches:
      - master
    paths:
      - 'game/**'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export and publish game
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: export
      uses: firebelley/godot-export@v1.1.0
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_export_templates.tpz
        godot_template_version: 3.2.stable
        relative_project_path: ./game
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
